.idea/workspace.xml, src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/java/Database/persistence/dto/ReviewDTO.java, src/main/java/Database/view/ReviewView.java, src/main/java/org/example/ForTest.java, src/main/java/org/example/Main.java, src/main/resources/config/config.xml, src/main/resources/sqlmapper/review.xml
=> 최대한 열심히 해써

.idea/workspace.xml, src/main/java/Database/persistence/dao/Dummy.java, src/main/java/Database/persistence/dto/MenuDTO.java, src/main/java/Database/persistence/dto/MenuHasOptionDTO.java, src/main/java/Database/persistence/dto/MenuOptionDTO.java, src/main/java/Database/persistence/dto/MenuSalesDTO.java, src/main/java/Database/persistence/dto/OptionDTO.java, src/main/java/Database/persistence/dto/OrderDTO.java, src/main/java/Database/persistence/dto/OrderViewDTO.java, src/main/java/Database/persistence/dto/OrderedMenuDTO.java, src/main/java/Database/persistence/dto/OrderedOptionDTO.java, src/main/java/Database/persistence/dto/ReviewDTO.java, src/main/java/Database/persistence/dto/StoreDTO.java, src/main/java/Database/persistence/dto/StoreSalesDTO.java, src/main/java/Database/persistence/dto/UserDTO.java
=> 직렬화, 역직렬화 구현 완

src/main/java/Network/Server/DeliveryServerThread.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
=> 고객 승인까지 + 명칭 수정

src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/Network/Server/DeliveryServerThread.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java, src/main/java/org/example/ForTest.java
=> 괄호 이슈 수정 및 관리자 점주 승인까지 

src/main/java/Database/persistence/dao/UserDAO.java, src/main/java/Network/Protocol/ProtocolType.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
DAO에서 login작업 리턴값으로 권한 주는걸로 바꾸어야함.
=> 로그인 익명으로 수정

src/main/java/Network/Protocol/ProtocolCode.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
=> 가게 메뉴 가격 수정까지

src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/Database/persistence/dto/NewOrderDTO.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/org/example/ForTest.java, src/main/java/org/example/Main.java, src/main/resources/config/config.xml, src/main/resources/sqlmapper/menu.xml, src/main/resources/sqlmapper/order.xml
=> 주문 새로만듬, 직렬화, 역직렬화 구현중

src/main/java/Network/Protocol/ProtocolCode.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
관리자 조회에서의 기능 중에 가게 전체 조회, 유저 전체 조회는 한글 파일에 해당 사항 없어서 뺏음.
리스트 직렬화, 조회 어떻게 할건 지 생각해봄
=> 리스트 받는 것이랑 조회 제외하고는 했음.

src/main/java/Database/persistence/dao/UserDAO.java, src/main/java/Database/persistence/dto/NewOrderDTO.java, src/main/java/org/example/ForTest.java, src/main/java/org/example/Main.java, src/main/resources/sqlmapper/user.xml
=> signIn 구현 했음

src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/org/example/Main.java, src/main/resources/sqlmapper/order.xml, src/main/resources/sqlmapper/user.xml
고객, 점주 회원가입 수정
주문 취소시 메뉴 restock 되게 변경
=> 회원가입, 주문취소 수정

src/main/java/Network/Server/DeliveryServer.java, src/main/java/Network/Server/DeliveryServerThread.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
일단 오늘은 여기까지 하고 내일 달려보자. 고생 많았다.
=> 왜 오류 나는지는 내일 물어보고 할 것.

src/main/java/Database/persistence/dao/UserDAO.java, src/main/resources/sqlmapper/user.xml
=> signIn UserDTO 반환하게 변경

src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
=> 로그인 DTO 리턴으로 수정

build.gradle, src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/java/Database/persistence/dao/UserDAO.java, src/main/java/Database/persistence/dto/NewOrderDTO.java, src/main/java/Database/persistence/dto/ReviewDTO.java, src/main/java/Database/persistence/dto/UserDTO.java, src/main/java/Database/view/ReviewView.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/org/example/ForTest.java, src/main/java/org/example/Main.java, src/main/resources/sqlmapper/review.xml, src/main/resources/sqlmapper/user.xml
=> user, order, review DAO 일단 수정함

src/main/java/Database/persistence/dto/IDTO.java, src/main/java/Network/MyListSerializer.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java, src/main/java/org/example/ForTest.java
=> 민준이 DB 수정한 거 전부 PR 받았음

src/main/java/Database/persistence/dao/UserDAO.java, src/main/java/Network/Server/DeliveryServerThread.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/org/example/Main.java
=> 개인정보 수정 수정 수정 수정

src/main/resources/sqlmapper/store.xml
=> showAcceptedStore 수정

src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/resources/sqlmapper/review.xml
=> showReview 수정

src/main/java/Network/MyListSerializer.java, src/main/java/Network/Protocol/ProtocolType.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
=> 메뉴 조회까지는 했음

src/main/java/Database/persistence/dao/StoreDAO.java, src/main/resources/sqlmapper/store.xml
=> store DAO에 getStoreName 만듬

src/main/java/Database/persistence/dao/StoreDAO.java, src/main/resources/sqlmapper/store.xml
=> store DAO에 getMyStoreList 만듬

src/main/java/Database/persistence/dao/UserDAO.java, src/main/resources/sqlmapper/user.xml
=> UserDAO에 getPendingStoreKeepers 생성

src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java
=> 미승인 점주 리스트

src/main/java/Database/view/UserView.java
=> UserView printAll 만듬

src/main/java/Database/persistence/dao/MenuDAO.java, src/main/java/Database/persistence/dao/OptionDAO.java, src/main/resources/sqlmapper/option.xml
=> MenuDAO에 insertMenuAll 수정

src/main/java/Database/view/OptionView.java
=> OptionView 생성

src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/java/Network/Server/ServerMessage.java, src/main/resources/sqlmapper/review.xml
ReviewDAO에 고객, 점주 입장 리뷰 조회 생성
페이징 처리도 함
입력은 현재 페이지
getUserReviewNum
getStoreReviewNum 
으로 총 리뷰 개수를 가져올 수 있음
=> ReviewDAO 업데이트

src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/resources/sqlmapper/review.xml
=> showUserReview 사용처 없음

src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/java/Database/persistence/dto/MenuDTO.java, src/main/java/Network/Protocol/ProtocolCode.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/Server/ServerPacket.java, src/main/java/Network/Server/SeverMain.java, src/main/java/Network/User/UserAPP.java, src/main/java/Network/User/UserMain.java, src/main/java/Network/User/UserMessage.java, src/main/java/Network/User/UserPacket.java, src/main/resources/sqlmapper/menu.xml
통계학 끝났고 뷰어 해야되고,
이쁘장하게 우리 딸 옷입히고, 출력하고 해야함.
=> 민준 + 찬진 퓨전

src/main/java/Database/persistence/dto/MenuDTO.java, src/main/java/Database/persistence/dto/MenuHasOptionDTO.java, src/main/java/Database/persistence/dto/MenuOptionDTO.java, src/main/java/Database/persistence/dto/MenuSalesDTO.java, src/main/java/Database/persistence/dto/NewOrderDTO.java, src/main/java/Database/persistence/dto/OptionDTO.java, src/main/java/Database/persistence/dto/OrderDTO.java, src/main/java/Database/persistence/dto/OrderedMenuDTO.java, src/main/java/Database/persistence/dto/OrderedOptionDTO.java, src/main/java/Database/persistence/dto/StoreDTO.java, src/main/java/Database/persistence/dto/StoreSalesDTO.java, src/main/java/Database/persistence/dto/UserDTO.java, src/main/resources/sqlmapper/order.xml
=> 각 DTO마다 인공 디폴트 생성자 생성

src/main/java/Database/persistence/dto/ReviewDTO.java, src/main/java/Network/User/UserAPP.java, src/main/java/Network/User/UserMessage.java, src/main/java/Network/User/UserPacket.java, src/main/java/Network/User/UserScreen.java
=> 리뷰 답글 등록 완성

src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/Network/User/UserAPP.java, src/main/java/Network/User/UserMessage.java, src/main/java/Network/User/UserPacket.java, src/main/java/Network/User/UserScreen.java, src/main/resources/sqlmapper/order.xml
=> 점주 주문 승인, 주문 취소 함수 DAO에 생성

src/main/java/Database/view/MenuView.java, src/main/java/Network/User/UserAPP.java
=> 메뉴 출력문 수정했어요~

src/main/java/Database/persistence/dao/OrderDAO.java, src/main/java/Database/persistence/dao/ReviewDAO.java, src/main/resources/sqlmapper/order.xml
=> 점주 배달완료 DAO에 만듬

src/main/java/Database/persistence/dto/OrderDTO.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/User/UserAPP.java, src/main/java/Network/User/UserMessage.java, src/main/java/Network/User/UserPacket.java, src/main/java/Network/User/UserScreen.java
=> judgeOrder 만들었어요 

src/main/java/Database/persistence/dao/MenuDAO.java, src/main/java/Database/persistence/dto/OrderDTO.java, src/main/java/Database/persistence/dto/ReviewDTO.java, src/main/java/Database/view/OrderView.java, src/main/java/Network/Server/ServerMessage.java, src/main/java/Network/User/UserAPP.java
=> 서버 수정 오류 해결

src/main/resources/sqlmapper/order.xml
=> 통계 안 나오는거 수정
